### ISSUE TITLE
Discord or Gitter

### ISSUE THREAD

**Issue by paezao** [shultays/bloodworks#135]
Hey does the project have a discord or gitter chat?

**Comment by shultays** [comment]
Not really, there is no one else on the project so it was never necessary :)

**Comment by paezao** [comment]
But what if someone wants to help out? Like myself? Lol

**Comment by shultays** [comment]
My original plan was getting help in the development process but that didn't work out. 

Currently I believe I am pretty close to release, just trying to finalize things and improving the gameplay so it is kinda hard to get help at this point. However if you want to add new content, you can add them as mods and if they are something that can be merged into actual game you can do it too.

I must warn you though, I couldn't create any documentation so adding new content might be kinda hard for now. You can use existing content as a reference though, they all in resources folder.

I am trying to make a demo for this week, I can open a discord channel after that
